kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "workshop"
spec:
  global:
    clusterName: "workshop-cluster"
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    dogstatsd:
      nonLocalTraffic: true
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            ddTraceVersions:
              java: "1"
              python: "4"
              js: "5"
              php: "1"
              dotnet: "3"
              ruby: "2"
    logCollection:
      enabled: true
      containerCollectAll: true
  override:
    nodeAgent:
      containers:
        agent:
          env:
            - name: DD_APM_NON_LOCAL_TRAFFIC
              value: "true"
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: "true"
            - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
              value: "true"
            - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
              value: "true"
            - name: DD_CONTAINER_INCLUDE_LOGS
              value: "all"
            - name: DD_KUBELET_TLS_VERIFY
              value: "false"
            - name: DD_KUBERNETES_KUBELET_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
