apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: auth
  namespace: workshop
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/auth`)
      kind: Rule
      services:
        - name: auth-function
          port: 8080
