apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forward-auth
  namespace: workshop
spec:
  forwardAuth:
    address: http://auth-function.workshop.svc.cluster.local/auth/validate
    trustForwardHeader: true
    authResponseHeaders:
      - X-User-CPF
      - X-User-Id
