# logs:
#   general:
#     level: DEBUG

# providers:
#   kubernetesCRD:
#     enabled: true
#   kubernetesIngress:
#     enabled: false

# ports:
#   web:
#     port: 80
#     nodePort: 31588
#     expose:
#       default: true

# service:
#   type: LoadBalancer
